version: '3.9'

services:
  web:
    build: .
    command: sh -c "poetry run python manage.py migrate && poetry run python manage.py csu && poetry run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: drf
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 260439
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  redis:
      image: redis:alpine
      ports:
        - "6379:6379"

  celery:
    build: .
    command: sh -c "poetry run celery -A drf-app worker --loglevel=info"
    depends_on:
      - redis
      - web
    env_file:
      - .env

  celery-beat:
    build: .
    command: sh -c "poetry run celery -A drf-app beat --loglevel=info"
    depends_on:
      - redis
      - web
    env_file:
      - .env

volumes:
  postgres_data:
  static_volume: